---
# file: roles\k8s_kubelet_kubeadm\tasks\main.yml

- name: Add kubernetes repository(/etc/yum.repos.d/kubernetes.repo)
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
    enabled: yes
#    exclude: kube*

- name: Disabling SELinux by running setenforce 0 is required to allow containers to access the host filesystem, which is required by pod networks for example. You have to do this until SELinux support is improved in the kubelet.
  shell: "setenforce 0"

- name: install kubelet, kubeadm
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - kubelet
    - kubeadm

- name: enable & start kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Generate /etc/sysctl.d/k8s.conf file
  copy:
    src: ../files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: reload (sysctl --system) /etc/sysctl.d/k8s.conf
  shell: "sysctl --system"
